#!/usr/bin/perl;

use strict;
use warnings;

[%# 

All templates automatically have access to:

Catalyst
 The catalyst context object. 

in_datafiles
 A hash of ROMEDB::Datafile objects, keyed by the names of
 the datafiles this process accepts, as specified in the 
 process_accepts table.

out_datafiles
 A hash of ROMEDB::Datafile objects, keyed by the names of
 the datafiles this process will generate, as specified
 in the process_creates table.

 plus anything that the component gives to
 $processor->arguments. Which you may or may not need.

 Remember, this is information available to the template
 at parsetime NOT the script at runtime

%]

##################################################################################
# Setup some common values.
###################################################################################
my \$rome_userdir          = "[% Catalyst.config.userdata _ '/' _ Catalyst.user.username%]";
my \$rome_username         = "[% Catalyst.user.username%]";
my \$rome_experiment_name  = "[% Catalyst.user.experiment.name %]";
my \$rome_experiment_owner = "[% Catalyst.user.experiment.owner.username %]";
